
export const EXPENSE_CATEGORIES = [
  "Mutton",
  "Australian Mutton",
  "Somali Mutton",
  "Omani Mutton",
  "Chicken",
  "Fresh Chicken",
  "Frozen Chicken",
  "Beef",
  "Fish",
  "Rawabi Juice",
  "Vegetable",
  "Grocery",
  "House Hold (Dubai)",
  "Petrol",
  "Rice Supplier",
  "Aluminium Packing",
  "Maintenance Expense",
  "Other Expense",
  "Salary",
  "Water",
  "Ghee Expense",
  "Sewage Water Removal",
  "Gas Supplier",
  "Air Ticket",
  "Electricity Bill",
  "Accommodation",
  "Driver Delivery Salary Charge",
  "Visa & Administration Expense",
  "Vehicle Maintenance Expense"
];
