import {
  IconAlertTriangle,
  IconArrowRight,
  IconCheck,
  IconChevronLeft,
  IconChevronRight,
  IconCommand,
  IconCreditCard,
  IconFile,
  IconFileText,
  IconHelpCircle,
  IconPhoto,
  IconDeviceLaptop,
  IconLayoutDashboard,
  IconLoader2,
  IconLogin,
  IconProps,
  IconShoppingBag,
  IconMoon,
  IconDotsVertical,
  IconPizza,
  IconPlus,
  IconSettings,
  IconSun,
  IconTrash,
  IconBrandTwitter,
  IconUser,
  IconUserCircle,
  IconUserEdit,
  IconUserX,
  IconX,
  IconLayoutKanban,
  IconBrandGithub,
  IconEye,
  IconEdit,
  IconChefHat,
  IconShare,
  IconRefresh,
  IconUsers,
  IconClipboardList,
  IconClock,
  IconCircleCheck,
  IconTrendingUp,
  IconCurrencyDollar,
  IconReceipt,
  IconPackage,
  IconCalendar,
  IconCalculator,
  IconMinus,
  IconScan
} from '@tabler/icons-react';

export type Icon = React.ComponentType<IconProps>;

export const Icons = {
  dashboard: IconLayoutDashboard,
  logo: IconCommand,
  login: IconLogin,
  close: IconX,
  product: IconShoppingBag,
  spinner: IconLoader2,
  kanban: IconLayoutKanban,
  chevronLeft: IconChevronLeft,
  chevronRight: IconChevronRight,
  trash: IconTrash,
  employee: IconUserX,
  post: IconFileText,
  page: IconFile,
  file: IconFile,
  userPen: IconUserEdit,
  user2: IconUserCircle,
  media: IconPhoto,
  settings: IconSettings,
  billing: IconCreditCard,
  ellipsis: IconDotsVertical,
  add: IconPlus,
  warning: IconAlertTriangle,
  user: IconUser,
  arrowRight: IconArrowRight,
  help: IconHelpCircle,
  pizza: IconPizza,
  sun: IconSun,
  moon: IconMoon,
  laptop: IconDeviceLaptop,
  github: IconBrandGithub,
  twitter: IconBrandTwitter,
  check: IconCheck,
  eye: IconEye,
  edit: IconEdit,
  chef: IconChefHat,
  share: IconShare,
  refresh: IconRefresh,
  users: IconUsers,
  clipboardList: IconClipboardList,
  clock: IconClock,
  circleCheck: IconCircleCheck,
  trendingUp: IconTrendingUp,
  dollar: IconCurrencyDollar,
  receipt: IconReceipt,
  package: IconPackage,
  calendar: IconCalendar,
  calculator: IconCalculator,
  minus: IconMinus,
  scan: IconScan
};